[project]
name = ""
version = ""
description = ""
authors = [{ name = "Julio Formiga", email = "julio.formiga@gmail.com" }]
license = { text = "MIT" }
dependencies = ["rich>=13.6.0", "pyinstaller>=6.1.0"]
requires-python = ">=3.8,<3.12"
