[project]
name = ""
version = ""
description = ""
authors = [{ name = "Julio Formiga", email = "julio.formiga@gmail.com" }]
license = { text = "MIT" }
dependencies = []
requires-python = ">=3.8,<=3.11"
